src/attachments/urls.py
from django.urls import path

from attachments import views

app_name = 'attachments'
urlpatterns = [
    path('<str:id>/<str:name>', views.GetAttachmentAPIView.as_view(), name='get-attachment'),
    path('upload-to-task', views.UploadTaskAttachmentAPIView.as_view(), name='upload-task-attachment'),
    path('upload-to-issue', views.UploadIssueAttachmentAPIView.as_view(), name='upload-issue-attachment'),
]

src/dashboard/adls/urls.py
from django.urls import path

from dashboard.adls import views

app_name = 'adls'
urlpatterns = [
    path('', views.AdlListView.as_view(), name='list'),
    path('<slug:id>/', views.AdlDetailView.as_view(), name='detail'),
    path('toggle-status/<slug:id>/', views.ToggleAdlStatusView.as_view(), name='toggle_status'),
    path('edit-profile/<slug:id>/', views.EditAdlProfileFormView.as_view(), name='edit_profile'),
]

src/dashboard/grm/urls.py
from django.urls import path

from dashboard.grm import views

app_name = 'grm'
urlpatterns = [
    path('', views.DashboardTemplateView.as_view(), name='dashboard'),
    path('start-new-issue', views.StartNewIssueView.as_view(), name='start_new_issue'),
    path('upload-issue-attachment/<int:issue>/', views.UploadIssueAttachmentFormView.as_view(),
         name='upload_issue_attachment'),
    path('delete-issue-attachment/<int:issue>/<str:attachment>/', views.IssueAttachmentDeleteView.as_view(),
         name='delete_issue_attachment'),
    path('issue-attachments/<int:issue>/', views.IssueAttachmentListView.as_view(), name='issue_attachments'),
    path('new-issue-step-1/<int:issue>/', views.NewIssueContactFormView.as_view(), name='new_issue_step_1'),
    path('new-issue-step-2/<int:issue>/', views.NewIssuePersonFormView.as_view(), name='new_issue_step_2'),
    path('new-issue-step-3/<int:issue>/', views.NewIssueDetailsFormView.as_view(), name='new_issue_step_3'),
    path('new-issue-step-4/<int:issue>/', views.NewIssueLocationFormView.as_view(), name='new_issue_step_4'),
    path('new-issue-step-5/<int:issue>/', views.NewIssueConfirmFormView.as_view(), name='new_issue_step_5'),
    path('new-issue-step-6/<int:issue>/', views.NewIssueConfirmationFormView.as_view(), name='new_issue_step_6'),
    path('review-issues', views.ReviewIssuesFormView.as_view(), name='review_issues'),
    path('issue-list', views.IssueListView.as_view(), name='issue_list'),
    path('issue-detail/<int:issue>/', views.IssueDetailsFormView.as_view(), name='issue_detail'),
    path('get-sensitive-issue-data/', views.GetSensitiveIssueDataView.as_view(), name='get_sensitive_issue_data'),
    path('edit-issue/<int:issue>/', views.EditIssueView.as_view(), name='edit_issue'),
    path('add-comment-to-issue/<int:issue>/', views.AddCommentToIssueView.as_view(), name='add_comment_to_issue'),
    path('issue-comments/<int:issue>/', views.IssueCommentListView.as_view(), name='issue_comments'),
    path('issue-status-buttons/<int:issue>/', views.IssueStatusButtonsTemplateView.as_view(),
         name='issue_status_buttons'),
    path('submit-issue-open-status/<int:issue>/', views.SubmitIssueOpenStatusView.as_view(),
         name='submit_issue_open_status'),
    path('submit-issue-research-result/<int:issue>/', views.SubmitIssueResearchResultFormView.as_view(),
         name='submit_issue_research_result'),
    path('submit-issue-reject-reason/<int:issue>/', views.SubmitIssueRejectReasonFormView.as_view(),
         name='submit_issue_reject_reason'),
    path('get-choices-for-next-administrative-level', views.GetChoicesForNextAdministrativeLevelView.as_view(),
         name='get_choices_for_next_administrative_level'),
    path('get-ancestor-administrative-levels', views.GetAncestorAdministrativeLevelsView.as_view(),
         name='get_ancestor_administrative_levels'),
    path('get-options-values', views.GetChoicesForOptionView.as_view(),
         name='get_options_values'),

]

src/dashboard/urls.py
from django.conf.urls import include
from django.urls import path

app_name = 'dashboard'
urlpatterns = [
    path('', include('dashboard.authentication.urls')),
    path('diagnostics/', include('dashboard.diagnostics.urls')),
    path('administrative-levels/', include('dashboard.adls.urls')),
    # path('participatory-budget/', include('dashboard.participatory_budget.urls')),
    # path('subprojects/', include('dashboard.subprojects.urls')),
    path('grm/', include('dashboard.grm.urls')),
    path('logs/', include('dashboard.logs.urls')),
    path('couchdb-proxy/', include('dashboard.couchdb_proxy.urls')),
]

src/grm/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

handler400 = 'dashboard.authentication.views.handler400'
handler403 = 'dashboard.authentication.views.handler403'
handler404 = 'dashboard.authentication.views.handler404'
handler500 = 'dashboard.authentication.views.handler500'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('attachments/', include('attachments.urls')),
    path('authentication/', include('authentication.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('dashboard.urls')),
]

schema_view = get_schema_view(
    openapi.Info(
        title="GRM API Documentation",
        default_version='v1',
        description="Test Documentation",
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    ]

src/dashboard/forms/widgets.py
from django import forms


class RadioSelect(forms.RadioSelect):
    input_type = 'radio'
    option_template_name = 'widgets/radio_option.html'

src/dashboard/grm/forms.py
from django import forms
from django.conf import settings
from django.utils.translation import gettext_lazy as _

from authentication.models import get_government_worker_choices
from client import get_db
from dashboard.forms.widgets import RadioSelect
from dashboard.grm import CHOICE_CONTACT, CITIZEN_TYPE_CHOICES, CONTACT_CHOICES, GENDER_CHOICES, MEDIUM_CHOICES
from grm.utils import (
    get_administrative_region_choices, get_base_administrative_id, get_administrative_regions_by_level,
    get_issue_age_group_choices, get_issue_category_choices, get_issue_citizen_group_1_choices,
    get_issue_citizen_group_2_choices, get_issue_status_choices, get_issue_type_choices, get_issue_options_choices
)

COUCHDB_GRM_DATABASE = settings.COUCHDB_GRM_DATABASE
MAX_LENGTH = 65000


class NewIssueContactForm(forms.Form):
    contact_medium = forms.ChoiceField(label=_('How does the citizen wish to be contacted?'), widget=RadioSelect,
                                       choices=MEDIUM_CHOICES)
    contact_type = forms.ChoiceField(label='', required=False, choices=CONTACT_CHOICES)
    contact = forms.CharField(label='', required=False)

    def __init__(self, *args, **kwargs):
        initial = kwargs.get('initial')
        doc_id = initial.get('doc_id')
        super().__init__(*args, **kwargs)

        grm_db = get_db(COUCHDB_GRM_DATABASE)

        self.fields['contact'].widget.attrs["placeholder"] = _("Please type the contact information")

        document = grm_db[doc_id]
        if 'contact_medium' in document:
            self.fields['contact_medium'].initial = document['contact_medium']
            if document['contact_medium'] == CHOICE_CONTACT:
                if 'type' in document['contact_information'] and document['contact_information']['type']:
                    self.fields['contact_type'].initial = document['contact_information']['type']
                if 'contact' in document['contact_information'] and document['contact_information']['contact']:
                    self.fields['contact'].initial = document['contact_information']['contact']
            else:
                self.fields['contact'].widget.attrs["class"] = "hidden"


class NewIssuePersonForm(forms.Form):
    citizen = forms.CharField(label=_('Enter name of the citizen'), required=False,
                              help_text=_('This is an optional field'))
    citizen_type = forms.ChoiceField(label=_(''), widget=RadioSelect, required=False,
                                     choices=CITIZEN_TYPE_CHOICES, help_text=_('This is an optional field'))
    citizen_age_group = forms.ChoiceField(label=_('Enter age group'), required=False,
                                          help_text=_('This is an optional field'))
    gender = forms.ChoiceField(label=_('Choose gender'), required=False, help_text=_('This is an optional field'),
                               choices=GENDER_CHOICES)
    citizen_group_1 = forms.ChoiceField(label=_('Occupancy status'), required=False,
                                        help_text=_('This is an optional field'))
    citizen_group_2 = forms.ChoiceField(label=_('Educational level'), required=False,
                                           help_text=_('This is an optional field'))


    def __init__(self, *args, **kwargs):
        initial = kwargs.get('initial')
        doc_id = initial.get('doc_id')
        super().__init__(*args, **kwargs)

        grm_db = get_db(COUCHDB_GRM_DATABASE)

        citizen_age_groups = get_issue_age_group_choices(grm_db)
        self.fields['citizen_age_group'].widget.choices = citizen_age_groups
        self.fields['citizen_age_group'].choices = citizen_age_groups

        citizen_group_1_choices = get_issue_citizen_group_1_choices(grm_db)
        self.fields['citizen_group_1'].widget.choices = citizen_group_1_choices
        self.fields['citizen_group_1'].choices = citizen_group_1_choices

        citizen_group_2_choices = get_issue_citizen_group_2_choices(grm_db)
        self.fields['citizen_group_2'].widget.choices = citizen_group_2_choices
        self.fields['citizen_group_2'].choices = citizen_group_2_choices

        document = grm_db[doc_id]

        if 'citizen' in document:
            self.fields['citizen'].initial = document['citizen']

        if 'citizen_type' in document:
            self.fields['citizen_type'].initial = document['citizen_type']

        if 'citizen_age_group' in document and document['citizen_age_group']:
            self.fields['citizen_age_group'].initial = document['citizen_age_group']['id']

        if 'gender' in document:
            self.fields['gender'].initial = document['gender']

        if 'citizen_group_1' in document and document['citizen_group_1']:
            self.fields['citizen_group_1'].initial = document['citizen_group_1']['id']

        if 'citizen_group_2' in document and document['citizen_group_2']:
            self.fields['citizen_group_2'].initial = document['citizen_group_2']['id']


class NewIssueDetailsForm(forms.Form):
    intake_date = forms.DateTimeField(label=_('Date of intake'), input_formats=['%d/%m/%Y'],
                                      help_text="Date when the issue was recorded on the GRM")
    issue_date = forms.DateTimeField(label=_('Date of issue'), input_formats=['%d/%m/%Y'],
                                     help_text="Date when the issue occurred")
    issue_type = forms.ChoiceField(label=_('What are you reporting'))
    issue_sub_type = forms.ChoiceField(label=_('The sub type of grievance'))
    category = forms.ChoiceField(label=_('The category of grievance'))
    component = forms.ChoiceField(label=_('Component'), required=False, help_text=_('This is an optional field'))
    sub_component = forms.ChoiceField(label=_('Sub Component'), required=False, help_text=_('This is an optional field'))
    description = forms.CharField(label=_('Briefly describe the issue'), max_length=2000, widget=forms.Textarea(
        attrs={'rows': '3', 'placeholder': _('Please describe the issue')}))
    ongoing_issue = forms.BooleanField(label=_('Current event or multiple occurrences'),
                                       widget=forms.CheckboxInput, required=False)

    def __init__(self, *args, **kwargs):
        initial = kwargs.get('initial')
        doc_id = initial.get('doc_id')
        super().__init__(*args, **kwargs)

        grm_db = get_db(COUCHDB_GRM_DATABASE)

        types = get_issue_type_choices(grm_db)
        self.fields['issue_type'].widget.choices = types
        self.fields['issue_type'].choices = types

        categories = get_issue_category_choices(grm_db)
        self.fields['category'].widget.choices = categories
        self.fields['category'].choices = categories

        sub_categories = get_issue_options_choices(grm_db, 'issue_sub_type')
        self.fields['issue_sub_type'].widget.choices = sub_categories
        self.fields['issue_sub_type'].choices = sub_categories

        components = get_issue_options_choices(grm_db, 'issue_component')
        self.fields['component'].widget.choices = components
        self.fields['component'].choices = components

        sub_components = get_issue_options_choices(grm_db, 'issue_sub_component')
        self.fields['sub_component'].widget.choices = sub_components
        self.fields['sub_component'].choices = sub_components

        self.fields['intake_date'].widget.attrs['class'] = self.fields['issue_date'].widget.attrs[
            'class'] = 'form-control datetimepicker-input'
        self.fields['intake_date'].widget.attrs['data-target'] = '#intake_date'
        self.fields['issue_date'].widget.attrs['data-target'] = '#issue_date'

        document = grm_db[doc_id]
        if 'description' in document and document['description']:
            self.fields['description'].initial = document['description']
        if 'issue_type' in document and document['issue_type']:
            self.fields['issue_type'].initial = document['issue_type']['id']
        if 'category' in document and document['category']:
            self.fields['category'].initial = document['category']['id']
        if 'issue_sub_type' in document and document['issue_sub_type']:
            self.fields['issue_sub_type'].initial = document['issue_sub_type']['id']
        if 'component' in document and document['component']:
            self.fields['component'].initial = document['component']['id']
        if 'sub_component' in document and document['sub_component']:
            self.fields['sub_component'].initial = document['sub_component']['id']
        if 'ongoing_issue' in document:
            self.fields['ongoing_issue'].initial = document['ongoing_issue']


class NewIssueLocationForm(forms.Form):
    administrative_region = forms.ChoiceField()
    administrative_region_value = forms.CharField(label='', required=False)

    def __init__(self, request_user, *args, **kwargs):
        initial = kwargs.get('initial')
        doc_id = initial.get('doc_id')
        super().__init__(*args, **kwargs)
        self.request_user = request_user

        eadl_db = get_db()
        label = get_administrative_regions_by_level(eadl_db)[0]['administrative_level'].title()
        self.fields['administrative_region'].label = label

        administrative_region_choices = get_administrative_region_choices(eadl_db)
        self.fields['administrative_region'].widget.choices = administrative_region_choices
        self.fields['administrative_region'].choices = administrative_region_choices
        self.fields['administrative_region'].widget.attrs['class'] = "region"
        self.fields['administrative_region_value'].widget.attrs['class'] = "hidden"

        country_id = eadl_db.get_query_result(
            {
                "type": 'administrative_level',
                "parent_id": None,
            }
        )[:][0]['administrative_id']
        # Prefill region with Current Logged in User

src/dashboard/authentication/views.py
from django.shortcuts import render
from rest_framework import status


def handler400(request, exception):
    return render(
        request,
        template_name='common/400.html',
        status=status.HTTP_400_BAD_REQUEST,
        content_type='text/html'
    )


def handler403(request, exception):
    return render(
        request,
        template_name='common/403.html',
        status=status.HTTP_403_FORBIDDEN,
        content_type='text/html'
    )


def handler404(request, exception):
    return render(
        request,
        template_name='common/404.html',
        status=status.HTTP_404_NOT_FOUND,
        content_type='text/html'
    )


def handler500(request):
    return render(
        request,
        template_name='common/500.html',
        status=status.HTTP_500_INTERNAL_SERVER_ERROR,
        content_type='text/html'
    )

src/dashboard/logs/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.translation import gettext_lazy as _
from django.views import generic

from dashboard.mixins import PageMixin


class DashboardTemplateView(PageMixin, LoginRequiredMixin, generic.TemplateView):
    template_name = 'common/under_construction.html'
    title = _('Logs')
    active_level1 = 'logs'

src/dashboard/subprojects/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.translation import gettext_lazy as _
from django.views import generic

from dashboard.mixins import PageMixin


class DashboardTemplateView(PageMixin, LoginRequiredMixin, generic.TemplateView):
    template_name = 'common/under_construction.html'
    title = _('Subprojects')
    active_level1 = 'subprojects'

src/dashboard/templates/grm/issue_comments.html
{% load static i18n custom_tags %}
{% for comment in comments %}
    <div class="row">
        <div class="col-6">
            {% with indexed_users|get:comment.id as color_index %}
                <div class="circle-icon float-left mr-2 navbar-{{ colors|next_in_circular_list:color_index }}">
                    <div class="center-32 pt-1 text-white text-bold-family">
                        {% get_initials comment.name %}
                    </div>
                </div>
            {% endwith %}
            <div class="text-bold-family">
                {{ comment.name }}
            </div>
            <div class="text-regular-family">
                {{ comment.due_at|string_to_date|date:'j-F-Y' }}
            </div>
        </div>
        <div class="col-6 text-right lh15 mt-3 text-regular-family">
            {% get_hour comment.due_at %}
        </div>
    </div>
    <div class="row border-bottom mt-2 mb-3">
        <div class="col-10 mb-2 text-regular-family mb-3">
            {{ comment.comment }}
        </div>
    </div>
{% empty %}
    <div class="row">
        <div class="col-12 text-center">
            {% translate 'No comments found' %}
        </div>
    </div>
{% endfor %}

src/dashboard/templates/grm/new_issue_details.html
{% extends 'layouts/base.html' %}
{% load bootstrap4 static i18n %}

{% block progress-bar %}
    {% include 'common/progress_bar.html' with percentage=50 %}
{% endblock progress-bar %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <div class="card">
                <img src="{% static 'images/bg-left-horizontal-waves.png' %}" class="bg-left-horizontal-waves"/>
                <form method="post">{% csrf_token %}
                    <div class="card-body">
                        <div class="row">
                            <div class="col-12">
                                <div class="fs20 lh46 mb-1 text-regular-family">
                                    {% translate 'Details of issue of Feedback' %}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-6">
                                <div class="fs56 lh46 text-primary text-bold-family mb-4">
                                    {% translate 'Step' %} 3
                                </div>
                                <div class="fs35 lh35 text-bold-family ">
                                    {% translate 'Basic Information' %}
                                </div>
                            </div>
                            <div class="col-6">
                                {% bootstrap_form form layout='horizontal' %}
                                <div class="overlay-wrapper">
                                    <div id="attachments"></div>
                                    <div class="overlay" id="load-attachments-spin">
                                        <i class="fas fa-2x fa-sync-alt fa-spin"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer mb-2">
                        <button type="submit" class="btn btn-primary btn-sm rounded-xl float-right">
                            {% translate "SAVE & NEXT" %}
                        </button>
                        <a href="{% url 'dashboard:grm:new_issue_step_2' doc.auto_increment_id %}"
                           class="btn btn-primary btn-sm rounded-xl float-right mr-4 disabled-on-submit">
                            <i class="fa fa-chevron-left mr-2"></i>
                            {% translate "BACK" %}
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block modals %}
    <div id="formModal" class="modal" role="dialog" aria-hidden="true" data-backdrop="static"></div>
{% endblock modals %}

{% block select2 %}
    <script type="text/javascript">
        $("#id_issue_type").select2({
            placeholder: "{% translate 'Click to select the report' %}",
            allowClear: true
        });
        $("#id_category").select2({
            placeholder: "{% translate 'Click to select an item' %}",
            allowClear: true
        });
        $("#id_issue_sub_type").select2({
            placeholder: "{% translate 'Click to select an item' %}",
            allowClear: true
        });
        $("#id_component").select2({
            placeholder: "{% translate 'Click to select an item' %}",
            allowClear: true
        });
        $("#id_sub_component").select2({
            placeholder: "{% translate 'Click to select an item' %}",
            allowClear: true
        });
    </script>
{% endblock select2 %}

{% block javascript %}
    {{ block.super }}
    <script src="{% static 'js/csrfSafeMethodAjax.js' %}"></script>
    <script src="{% static 'js/formAjaxSubmit.js' %}"></script>
    <script src="{% static 'js/dynamicOptionSelector.js' %}"></script>
    <script type="text/javascript">
        let load_attachments_spin = $('#load-attachments-spin');

        let get_choices_url = '{% url 'dashboard:grm:get_options_values' %}';
        $("#id_issue_type").change(function () {
            if ($(this).val() && $(this).val() !== '') {
                var data = {'type': 'issue_sub_type', 'parent_id': $(this).val()};
                loadData(get_choices_url, data, 'id_issue_sub_type');
            }
        });

        $("#id_issue_sub_type").change(function () {
            if ($(this).val() && $(this).val() !== '') {
                var data = {'type': 'issue_category', 'parent_id': $(this).val()};
                loadData(get_choices_url, data, 'id_category');
            }
        });

        $("#id_component").change(function () {
            if ($(this).val() && $(this).val() !== '') {
                var data = {'type': 'issue_sub_component', 'parent_id': $(this).val()};
                loadData(get_choices_url, data, 'id_sub_component');
            }
        });

        function loadAttachments() {
            load_attachments_spin.show();
            $('#attachments').load("{% url 'dashboard:grm:issue_attachments' doc.auto_increment_id %}", function (
                response, status, xhr) {
                if (status === "error") {
                    alert(error_server_message + "Error " + response.status);
                }
                load_attachments_spin.hide();
                $('#add_attachment').click(function () {
                    let url = "{% url 'dashboard:grm:upload_issue_attachment' doc.auto_increment_id %}";
                    file_form_ajax.load_form('#form', modal, url, false, true);
                });
            });
        }

        $(document).ready(function () {
            loadAttachments();
        });


        class FileFormAjaxSubmit extends FormAjaxSubmit {
            submitted_form() {
                loadAttachments();
            }
        }

        let file_form_ajax = new FileFormAjaxSubmit();
        let modal = $('#formModal');

        $('b[role="presentation"]').hide();
        $('.select2-selection__arrow').append(
            '<i class="fas fa-chevron-circle-down text-primary" style="margin-top:12px;"></i>');
        let dp1 = '<div class="input-group-prepend" data-target="#{id}" data-toggle="datetimepicker">' +
            '<div class="input-group-text"><i class="fa fa-calendar text-primary"></i></div></div>';
        let dp2 = '<div class="input-group date" id="{id}" data-target-input="nearest"></div>';
        $('#id_intake_date').before(dp1.replace('{id}', 'intake_date')).parent().wrapInner(
            dp2.replace('{id}', 'intake_date'));
        $('#id_issue_date').before(dp1.replace('{id}', 'issue_date')).parent().wrapInner(
            dp2.replace('{id}', 'issue_date'));

        let help_text1 = $('#intake_date small')[0];
        $('#intake_date small').remove();
        $('#intake_date').after(help_text1);

        let help_text2 = $('#issue_date small')[0];
        $('#issue_date small').remove();
        $('#issue_date').after(help_text2);

        //Datemask dd/mm/yyyy
        $('.datetimepicker-input').inputmask({alias: "datetime", inputFormat: "dd/mm/yyyy"});

        let defaultDate = Date.now();
        {% if doc.intake_date %}
            defaultDate = moment("{{ doc.intake_date }}", "YYYY-MM-DD");
        {% endif %}
        $('#intake_date').datetimepicker({
            maxDate: Date.now(),
            useCurrent: false,
            defaultDate: defaultDate,
            format: "DD/MM/YYYY",
        });
        {% if doc.issue_date %}
            defaultDate = moment("{{ doc.issue_date }}", "YYYY-MM-DD");
        {% else %}
            defaultDate = false;
        {% endif %}
        $('#issue_date').datetimepicker({
            maxDate: Date.now(),
            useCurrent: false,
            defaultDate: defaultDate,
            format: "DD/MM/YYYY",
            widgetPositioning: {
                vertical: 'bottom',
            }
        });

        $(document).on('click', '.delete-attachment', function () {
            $.ajax({
                url: $(this).data('url'),
                type: 'POST'
            })
                .fail(function (data) {
                    alert(error_server_message + "Error " + data.status);
                })
                .done(function (data) {
                    loadAttachments();
                    showPopupMessage(data.msg);
                })
        });
    </script>
{% endblock javascript %}

src/dashboard/templates/grm/new_issue_person.html
{% extends 'layouts/base.html' %}
{% load bootstrap4 static i18n %}

{% block progress-bar %}
    {% include 'common/progress_bar.html' with percentage=33 %}
{% endblock progress-bar %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <div class="card">
                <img src="{% static 'images/bg-left-horizontal-waves.png' %}" class="bg-left-horizontal-waves"/>
                <form method="post">{% csrf_token %}
                    <div class="card-body">
                        <div class="row">
                            <div class="col-12">
                                <div class="fs20 lh46 mb-1 text-regular-family">
                                    {% translate 'Enter New Issue' %}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-6">
                                <div class="fs56 lh46 text-primary text-bold-family mb-4">
                                    {% translate 'Step' %} 2
                                </div>
                                <div class="fs35 lh35 text-bold-family ">
                                    {% translate 'Name of Person or Group' %}
                                </div>
                            </div>
                            <div class="col-6">
                                {% bootstrap_form form layout='horizontal' %}
                            </div>
                        </div>
                    </div>
                    <div class="card-footer mb-2">
                        <button type="submit" class="btn btn-primary btn-sm rounded-xl float-right">
                            {% translate "SAVE & NEXT" %}
                        </button>
                        <a href="{% url 'dashboard:grm:new_issue_step_1' doc.auto_increment_id %}"
                           class="btn btn-primary btn-sm rounded-xl float-right mr-4 disabled-on-submit">
                            <i class="fa fa-chevron-left mr-2"></i>
                            {% translate "BACK" %}
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block select2 %}
    <script type="text/javascript">
        $("#id_citizen_age_group").select2({
            placeholder: "{% translate 'Click to select age group' %}",
            allowClear: true
        });
        $("#id_gender").select2({
            placeholder: "{% translate 'Click to select gender' %}",
            allowClear: true
        });
        {% translate 'Click to select religion, nationality' as empty_group_msg %}
        $("#id_citizen_group_1").select2({
            placeholder: "{{ empty_group_msg }}",
            allowClear: true
        });
        $("#id_citizen_group_2").select2({
            placeholder: "{{ empty_group_msg }}",
            allowClear: true
        });
        {% translate 'Click to select occupation status' as empty_group_msg_occupation %}
        $("#id_citizen_occupation").select2({
            placeholder: "{{ empty_group_msg_occupation }}",
            allowClear: true
        });
        {% translate 'Click to select educational level' as empty_group_msg_educational_level %}
        $("#id_citizen_educational_level").select2({
            placeholder: "{{ empty_group_msg_educational_level }}",
            allowClear: true
        });
    </script>
{% endblock select2 %}

{% block javascript %}
    {{ block.super }}
    <script src="{% static 'js/deselectableRadios.js' %}"></script>
    <script type="text/javascript">
        deselectableRadios("id_citizen_type");
    </script>
{% endblock javascript %}